import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";

import { ToastContainer} from 'react-toastify';
import Navbar from "../components/common/Navbar";
import Footer from "../components/common/Footer";
import { UserProvider } from "../context/userContext";
import { EventProvider } from "../context/eventContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "NovaNextGen",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <UserProvider>
        <EventProvider>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar/>
        {children}
        <Footer/>
        <ToastContainer/>
      </body>
      </EventProvider>
      </UserProvider>
    </html>
  );
}
